/* ============================================================
   DADOS MOCKADOS — Fazenda Fernandina

   Estes são dados fictícios usados para desenvolver a interface
   sem precisar do banco de dados Supabase ainda.

   Na Fase 3, quando o banco estiver configurado, vamos substituir
   esses dados pelas queries reais do arquivo lib/supabase.ts.

   "Mock" = simulação, imitação dos dados reais.
   ============================================================ */

import type { Criacao, Animal } from "./types";

/* -------------------------------------------------------
   As 6 criações da Fazenda Fernandina
   Cada uma vira um card na home e uma página /categoria/[slug]
   ------------------------------------------------------- */
export const CRIACOES_MOCK: Criacao[] = [
  {
    id: "1",
    slug: "cavalos", // aparece na URL: /categoria/cavalos
    nome: "Haras Fernandina",
    categoria: "CAVALOS",
    descricao:
      "Referência nacional na criação do Mangalarga Marchador, com excelência reconhecida na seleção de pampa de preto. A marcha nos define, a excelência nos diferencia.",
    tagline: "A Marcha é o que Nos Move.",
    instagram: "@harasfernandina",
    /* Logo oficial do Haras Fernandina como hero da criação */
    foto_hero: "/haras-fernandina.png",
    criado_em: "2026-01-01",
  },
  {
    id: "2",
    slug: "alpacas",
    nome: "Alpacas dos Andes",
    categoria: "ALPACAS",
    descricao:
      "Criação de alpacas e lhamas com genética de alto padrão, diretamente dos Andes peruanos, 100% puras e rigorosamente selecionadas.",
    tagline: "Alta qualidade genética dos Andes Peruanos.",
    instagram: "@alpacasdosandes",
    /* Logo oficial das Alpacas dos Andes como hero da criação */
    foto_hero: "/alpacas-logo.png",
    criado_em: "2026-01-01",
  },
  {
    id: "3",
    slug: "mini-cabras",
    nome: "Mini Cabras dos Alpes",
    categoria: "MINI CABRAS",
    descricao:
      "Criação de mini cabras com padrão definido, baseada em seleção consistente e manejo de alto nível.",
    tagline: "Pequenas, dóceis e cheias de vida.",
    instagram: "@minicabrasdosalpes",
    foto_hero: "/mini-cabras-logo.png",
    criado_em: "2026-01-01",
  },
  {
    id: "4",
    slug: "mini-porcos",
    nome: "Mini-Porcos da Serra",
    categoria: "MINI PORCOS",
    descricao:
      "Criação de mini porcos com seleção criteriosa e controle de qualidade em cada geração.",
    tagline: "Excelência se mantém com consistência.",
    instagram: "@miniporcosdaserra",
    foto_hero: "/mini-porcos-logo.png",
    criado_em: "2026-01-01",
  },
  {
    id: "5",
    slug: "coelhos",
    nome: "Coelhos da Montanha",
    categoria: "COELHOS",
    descricao:
      "Criação especializada de coelhos, com foco em genética, padrão e qualidade de linhagem.",
    tagline: "Consistência se constrói geração após geração.",
    instagram: "@coelhosdamontanha",
    foto_hero: "/coelhos-logo.png",
    criado_em: "2026-01-01",
  },
];

/* -------------------------------------------------------
   Animais de exemplo para desenvolvimento
   ------------------------------------------------------- */
export const ANIMAIS_MOCK: Animal[] = [
  // ---- CAVALOS — ÉGUAS ----
  {
    id: "a1",
    criacao_id: "1",
    nome: "Bela",
    raca: "Quarto de Milha",
    idade: "2 anos",
    sexo: "Fêmea",
    pelagem: "Alazã",
    grupo: "Éguas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: "Whiz N Shine",
    genealogia_mae: "Miss Poco Bars",
    descricao: "Égua Quarto de Milha de alta performance.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "a2",
    criacao_id: "1",
    nome: "Jasmini SF do Mandacaru",
    raca: "Mangalarga Marchador",
    idade: null,
    sexo: "Fêmea",
    pelagem: "Pampa de Preto",
    grupo: "Éguas",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Égua Mangalarga Marchador de pampa de preto impecável. Jasmini carrega no corpo a assinatura genética do Haras Fernandina — cada mancha, um traço de identidade. Beleza que chama atenção antes mesmo de dar o primeiro passo.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/jasmini-sf-do-mandacaru-egua.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "a3",
    criacao_id: "1",
    nome: "Araponga do Candieiro da Marcha",
    raca: "Mangalarga Marchador",
    idade: null,
    sexo: "Fêmea",
    pelagem: "Pampa de Preto",
    grupo: "Éguas",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Pampa de preto de conformação rara e presença que paralisa. Araponga do Candieiro da Marcha é do tipo que não precisa se mover para impressionar — mas quando marcha, não deixa dúvidas.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/araponga-do-candieiro-egua.jpg", principal: true, ordem: 1 }],
  },

  {
    id: "a14",
    criacao_id: "1",
    nome: "Uganda do Espinho Preto",
    raca: "Mangalarga Marchador",
    idade: null,
    sexo: "Fêmea",
    pelagem: "Preta",
    grupo: "Éguas",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Preta uniforme, sem uma mancha, sem uma concessão. Uganda do Espinho Preto carrega na pelagem a mesma intensidade da sua genética — robusta, elegante e de presença inconfundível no campo.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/uganda-do-espinho-preto-egua.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "a13",
    criacao_id: "1",
    nome: "Dama de Salto Boa Vista",
    raca: "Mangalarga Marchador",
    idade: null,
    sexo: "Fêmea",
    pelagem: "Pampa de Preto",
    grupo: "Éguas",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Branca com marcações negras que contam uma história de elegância e seleção. A Dama de Salto Boa Vista tem o porte de quem foi criada para ser admirada — e a genética para perpetuar o que o Haras Fernandina tem de melhor.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/dama-de-salto-boa-vista-egua.jpg", principal: true, ordem: 1 }],
  },

  {
    id: "a15",
    criacao_id: "1",
    nome: "Naja JFS",
    raca: "Mangalarga Marchador",
    idade: null,
    sexo: "Fêmea",
    pelagem: "Pampa de Preto com crina dourada",
    grupo: "Éguas",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Pampa de preto com crina e cauda douradas — uma combinação que a natureza raramente assina. Naja JFS é o tipo de égua que para o campo quando passa. Beleza singular e genética que justifica cada olhar.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/naja-jfs-egua.jpg", principal: true, ordem: 1 }],
  },

  // ---- CAVALOS — GARANHÕES ----
  {
    id: "a4",
    criacao_id: "1",
    nome: "Lorde do Monteiro",
    raca: "Mangalarga Marchador",
    idade: "11 anos",
    sexo: "Macho",
    pelagem: "Pampa de Preto",
    grupo: "Garanhões",
    status: "reproducao",
    andamento: "Picada",
    genealogia_pai: "Elfo do Porto Azul",
    genealogia_mae: "Quermesse da Santa Esmeralda",
    descricao: "Um fenômeno de marcha picada e genética irrepreensível. Filho do Elfo do Porto Azul com Quermesse da Santa Esmeralda, o Lorde não apenas carrega um nome — ele o justifica a cada passada. Coberturas disponíveis.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/lorde-do-monteiro-garanhao.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "a5",
    criacao_id: "1",
    nome: "Ébano CS VB",
    raca: "Mangalarga Marchador",
    idade: "11 anos",
    sexo: "Macho",
    pelagem: "Pampa de Preto",
    grupo: "Garanhões",
    status: "reproducao",
    andamento: "Picada",
    genealogia_pai: "Seu Chico Tandy",
    genealogia_mae: "Cabiúna da Lapinha",
    descricao: "Ícone nacional. Filho do Seu Chico Tandy com Cabiúna da Lapinha, o Ébano CS VB não precisa se apresentar — sua linhagem fala por ele. Marcha picada de rara perfeição, presença que intimida e genética que transforma rebanhos. Coberturas disponíveis.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/ebano-cs-vb-garanhao.jpg", principal: true, ordem: 1 }],
  },

  // ---- CAVALOS — POTROS ----
  {
    id: "a6",
    criacao_id: "1",
    nome: "Diana",
    raca: "Mangalarga",
    idade: "5 meses",
    sexo: "Fêmea",
    pelagem: "Tordilha Manchada",
    grupo: "Potros",
    status: "disponivel",
    andamento: "Batida",
    genealogia_pai: "Apollo",
    genealogia_mae: "Serena",
    descricao:
      "Potrinha Mangalarga de conformação perfeita, filha de pai campeão nacional. Criada à pata da mãe no campo.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "a7",
    criacao_id: "1",
    nome: "Zeus",
    raca: "Quarto de Milha",
    idade: "4 meses",
    sexo: "Macho",
    pelagem: "Alazão",
    grupo: "Potros",
    status: "disponivel",
    andamento: null,
    genealogia_pai: "Smart Chic Olena",
    genealogia_mae: "Bela Poco Whiz",
    descricao: "Potro Quarto de Milha com futuro promissor.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "a8",
    criacao_id: "1",
    nome: "Heitor",
    raca: "Lusitano",
    idade: "1 ano",
    sexo: "Macho",
    pelagem: "Castanho",
    grupo: "Potros",
    status: "disponivel",
    andamento: null,
    genealogia_pai: "Dom Sebastião VII",
    genealogia_mae: "Fátima de Lisboa II",
    descricao: "Potro Lusitano de linhagem nobre.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- CAVALOS — EMBRIÕES ----
  {
    id: "a9",
    criacao_id: "1",
    nome: "Embrião Apollo × Serena I",
    raca: "Mangalarga Marchador",
    idade: "Disponível para implante",
    sexo: "Indefinido",
    pelagem: "A definir",
    grupo: "Embriões",
    status: "disponivel",
    andamento: "Batida",
    /* Genealogia obrigatória para embriões — define o valor do lote */
    genealogia_pai: "Apollo",
    genealogia_mae: "Serena",
    descricao: "Embrião Mangalarga Marchador de marcha batida, cruzamento dos melhores exemplares do Haras Fernandina.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "a10",
    criacao_id: "1",
    nome: "Embrião Apollo × Ísis I",
    raca: "Mangalarga × Árabe",
    idade: "Disponível para implante",
    sexo: "Indefinido",
    pelagem: "A definir",
    grupo: "Embriões",
    status: "disponivel",
    andamento: null,
    genealogia_pai: "Apollo",
    genealogia_mae: "Ísis",
    descricao: "Embrião de cruzamento especial Mangalarga Marchador × Árabe, combinação rara de elegância e marcha.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- CAVALOS — COBERTURAS ----
  {
    id: "a11",
    criacao_id: "1",
    nome: "Cobertura Lorde do Monteiro — Temporada 2026",
    raca: "Mangalarga Marchador",
    idade: "Garanhão 11 anos",
    sexo: "Macho",
    pelagem: "Pampa de Preto",
    grupo: "Coberturas",
    status: "disponivel",
    andamento: "Picada",
    genealogia_pai: "Elfo do Porto Azul",
    genealogia_mae: "Quermesse da Santa Esmeralda",
    descricao: "Cobertura com o garanhão Lorde do Monteiro, pampa de preto de marcha picada e genealogia irrepreensível. Vagas limitadas para a temporada 2026.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/lorde-do-monteiro-garanhao.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "a12",
    criacao_id: "1",
    nome: "Cobertura Ébano CS VB — Temporada 2026",
    raca: "Mangalarga Marchador",
    idade: "Garanhão 11 anos",
    sexo: "Macho",
    pelagem: "Pampa de Preto",
    grupo: "Coberturas",
    status: "disponivel",
    andamento: "Picada",
    genealogia_pai: "Seu Chico Tandy",
    genealogia_mae: "Cabiúna da Lapinha",
    descricao: "Cobertura com o ícone nacional Ébano CS VB, filho do Seu Chico Tandy com Cabiúna da Lapinha. Marcha picada de rara perfeição. Vagas limitadas para a temporada 2026.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/ebano-cs-vb-garanhao.jpg", principal: true, ordem: 1 }],
  },

  // ---- MINI CABRAS — FILHOTES ----
  {
    id: "c1",
    criacao_id: "3",
    nome: "Bolinha",
    raca: "Pigmeu",
    idade: "3 meses",
    sexo: "Fêmea",
    pelagem: "Branca e Preta",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Pigmeu dócil e bem socializada.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "c2",
    criacao_id: "3",
    nome: "Pintinha",
    raca: "Anã Nigeriana",
    idade: "2 meses",
    sexo: "Fêmea",
    pelagem: "Caramelo",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Anã Nigeriana com coloração rara.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI CABRAS — MATRIZES FÊMEAS ----
  {
    id: "c3",
    criacao_id: "3",
    nome: "Estrela",
    raca: "Pigmeu",
    idade: "2 anos",
    sexo: "Fêmea",
    pelagem: "Preta",
    grupo: "Matrizes",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Matriz Pigmeu com excelente histórico reprodutivo.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "c4",
    criacao_id: "3",
    nome: "Flor",
    raca: "Anã Nigeriana",
    idade: "3 anos",
    sexo: "Fêmea",
    pelagem: "Branca",
    grupo: "Fêmeas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Anã Nigeriana selecionada por conformação e docilidade.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI CABRAS — MACHOS ----
  {
    id: "c5",
    criacao_id: "3",
    nome: "Trovão",
    raca: "Pigmeu",
    idade: "1 ano",
    sexo: "Macho",
    pelagem: "Cinza",
    grupo: "Machos",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Macho Pigmeu de ótima conformação e temperamento equilibrado.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI PORCOS — FILHOTES ----
  {
    id: "d1",
    criacao_id: "4",
    nome: "Bolota",
    raca: "Mini Pig",
    idade: "2 meses",
    sexo: "Fêmea",
    pelagem: "Rosada",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Mini Pig dócil e bem socializada.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "d2",
    criacao_id: "4",
    nome: "Farofa",
    raca: "Mini Pig",
    idade: "3 meses",
    sexo: "Macho",
    pelagem: "Preta e Branca",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Mini Pig com pelagem rara e temperamento tranquilo.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI PORCOS — MATRIZES ----
  {
    id: "d3",
    criacao_id: "4",
    nome: "Rosinha",
    raca: "Mini Pig",
    idade: "2 anos",
    sexo: "Fêmea",
    pelagem: "Rosada",
    grupo: "Matrizes",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Matriz Mini Pig com excelente histórico reprodutivo.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI PORCOS — FÊMEAS ----
  {
    id: "d4",
    criacao_id: "4",
    nome: "Pipoca",
    raca: "Mini Pig",
    idade: "1 ano",
    sexo: "Fêmea",
    pelagem: "Branca",
    grupo: "Fêmeas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Mini Pig de porte pequeno e temperamento equilibrado.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- MINI PORCOS — MACHOS ----
  {
    id: "d5",
    criacao_id: "4",
    nome: "Carvão",
    raca: "Mini Pig",
    idade: "1 ano",
    sexo: "Macho",
    pelagem: "Preta",
    grupo: "Machos",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Macho Mini Pig de pelagem escura e constituição robusta.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- COELHOS — FILHOTES ----
  {
    id: "e1",
    criacao_id: "5",
    nome: "Algodão",
    raca: "Angorá",
    idade: "2 meses",
    sexo: "Fêmea",
    pelagem: "Branca",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Angorá com pelo denso e temperamento dócil.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },
  {
    id: "e2",
    criacao_id: "5",
    nome: "Canela",
    raca: "Mini Rex",
    idade: "3 meses",
    sexo: "Macho",
    pelagem: "Caramelo",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Filhote Mini Rex com pelagem aveludada e coloração exuberante.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- COELHOS — MATRIZES ----
  {
    id: "e3",
    criacao_id: "5",
    nome: "Neve",
    raca: "Angorá",
    idade: "2 anos",
    sexo: "Fêmea",
    pelagem: "Branca",
    grupo: "Matrizes",
    status: "reproducao",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Matriz Angorá com histórico reprodutivo consistente.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- COELHOS — FÊMEAS ----
  {
    id: "e4",
    criacao_id: "5",
    nome: "Mochi",
    raca: "Holland Lop",
    idade: "1 ano",
    sexo: "Fêmea",
    pelagem: "Cinza",
    grupo: "Fêmeas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Holland Lop com orelhas caídas e personalidade afetiva.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- COELHOS — MACHOS ----
  {
    id: "e5",
    criacao_id: "5",
    nome: "Thor",
    raca: "Mini Rex",
    idade: "1 ano",
    sexo: "Macho",
    pelagem: "Preta",
    grupo: "Machos",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Macho Mini Rex de pelagem aveludada e porte compacto.",
    ativo: false,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [],
  },

  // ---- ALPACAS — FILHOTES ----
  {
    id: "b1",
    criacao_id: "2",
    nome: "Nuvem",
    raca: "Huacaya",
    idade: "8 meses",
    sexo: null,
    pelagem: "Branca",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Huacaya de lã branca e densa como algodão colhido no alto dos Andes. Fleece volumoso, uniforme e de toque macio — uma peça rara para quem busca qualidade genética desde cedo.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/nuvem-alpaca-huacaya.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b2",
    criacao_id: "2",
    nome: "Areia",
    raca: "Huacaya",
    idade: "10 meses",
    sexo: null,
    pelagem: "Champagne",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Huacaya champagne com pescoço claro e corpo dourado. Fleece encrespado e bem distribuído — a combinação de tonalidade e estrutura de fibra que todo criador procura.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/areia-alpaca-huacaya.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b3",
    criacao_id: "2",
    nome: "Mel",
    raca: "Huacaya",
    idade: "9 meses",
    sexo: null,
    pelagem: "Bege/mel",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Huacaya de pelagem mel uniforme e fleece bem encorpado. Conformação sólida e temperamento tranquilo — filhote de alto potencial para reprodução e fibra.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/mel-alpaca-huacaya.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b4",
    criacao_id: "2",
    nome: "Duna",
    raca: "Huacaya",
    idade: "8 meses",
    sexo: null,
    pelagem: "Areia com tons terrosos",
    grupo: "Filhotes",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Huacaya de pelagem arenosa com gradiente terroso — uma das colorações mais valorizadas no mercado de fibra. Ativa, curiosa e com lã que já se destaca aos primeiros meses.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/duna-alpaca-huacaya.jpg", principal: true, ordem: 1 }],
  },

  // ---- ALPACAS — LHAMAS ----
  {
    id: "b6",
    criacao_id: "2",
    nome: "Mosaico",
    raca: "Lhama Qara",
    idade: "1 ano",
    sexo: "Macho",
    pelagem: "Bicolor — branco e castanho",
    grupo: "Lhamas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Macho Qara bicolor de rara beleza — pescoço e face brancos, corpo em castanho intenso. Uma combinação que a natureza assina com perfeição.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/mosaico-lhama-qara.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b7",
    criacao_id: "2",
    nome: "Canela",
    raca: "Lhama Qara",
    idade: "1 ano",
    sexo: "Fêmea",
    pelagem: "Castanha",
    grupo: "Lhamas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Qara de pelagem castanha uniforme e porte esguio. Elegante como as terras altas de onde vem — simples na cor, inconfundível na presença.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/canela-lhama-qara.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b8",
    criacao_id: "2",
    nome: "Marfim",
    raca: "Lhama Qara",
    idade: "1 ano",
    sexo: "Fêmea",
    pelagem: "Creme",
    grupo: "Lhamas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Qara de tom creme suave e pescoço claro. Carrega a delicadeza dos Andes em cada detalhe — discreta na cor, marcante na presença.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/marfim-lhama-qara.jpg", principal: true, ordem: 1 }],
  },
  {
    id: "b9",
    criacao_id: "2",
    nome: "Âmbar",
    raca: "Lhama Qara",
    idade: "1 ano",
    sexo: "Fêmea",
    pelagem: "Castanho escuro",
    grupo: "Lhamas",
    status: "disponivel",
    andamento: null,
    genealogia_pai: null,
    genealogia_mae: null,
    descricao: "Fêmea Qara de castanho intenso e pernas claras com marcações naturais. Tem o tom quente do entardecer andino — e a energia de quem nunca fica parada.",
    ativo: true,
    criado_em: "2026-01-01",
    atualizado_em: "2026-01-01",
    fotos_animais: [{ url: "/ambar-lhama-qara.jpg", principal: true, ordem: 1 }],
  },
];

/* -------------------------------------------------------
   Categorias de filtro por criação
   Cada criação tem suas próprias categorias de animal
   ------------------------------------------------------- */
export const CATEGORIAS_POR_CRIACAO: Record<string, string[]> = {
  cavalos: ["Éguas", "Garanhões", "Potros", "Embriões", "Coberturas"],
  alpacas: ["Filhotes", "Adultos", "Lhamas"],
  "mini-cabras": ["Filhotes", "Matrizes", "Fêmeas", "Machos"],
  "mini-porcos": ["Filhotes", "Matrizes", "Fêmeas", "Machos"],
  coelhos:       ["Filhotes", "Matrizes", "Fêmeas", "Machos"],
};

/* -------------------------------------------------------
   Descrição longa de cada criação para a página interna
   ------------------------------------------------------- */
export const DESCRICAO_CRIACAO: Record<string, string> = {
  cavalos:
    "Referência nacional na criação do Mangalarga Marchador, com excelência reconhecida na seleção de pampa de preto. Cada animal é cuidadosamente selecionado por conformação, marcha e temperamento, garantindo padrão genético de alto nível em cada geração.",
  alpacas:
    "Criação de alpacas e lhamas com genética de alto padrão, diretamente dos Andes peruanos, 100% puras e rigorosamente selecionadas. Nossa fibra é referência pela densidade, finura e uniformidade.",
  "mini-cabras":
    "Criação de mini cabras com padrão definido, baseada em seleção consistente e manejo de alto nível. Animais dóceis e saudáveis, criados com atenção individualizada.",
  "mini-porcos":
    "Criação de mini porcos com seleção criteriosa e controle de qualidade em cada geração. Animais domésticos especializados com saúde garantida e temperamento equilibrado.",
  coelhos:
    "Criação especializada de coelhos de raças puras, com foco em genética, padrão e qualidade de linhagem. Variedades selecionadas para beleza, saúde e temperamento.",
};

/* -------------------------------------------------------
   Informações de Instagram por criação
   ------------------------------------------------------- */
export const INSTAGRAM_INFO: Record<
  string,
  { handle: string; subtitulo: string; url: string }
> = {
  cavalos: {
    handle: "@harasfernandina",
    subtitulo: "Bastidores, novidades e animais disponíveis.",
    url: "https://instagram.com/harasfernandina",
  },
  alpacas: {
    handle: "@alpacasdosandes",
    subtitulo: "Acompanhe nossas alpacas e lhamas.",
    url: "https://instagram.com/alpacasdosandes",
  },
  "mini-cabras": {
    handle: "@minicabrasdosalpes",
    subtitulo: "Novidades e filhotes disponíveis.",
    url: "https://instagram.com/minicabrasdosalpes",
  },
  "mini-porcos": {
    handle: "@miniporcosdaserra",
    subtitulo: "Acompanhe nossas criações.",
    url: "https://instagram.com/miniporcosdaserra",
  },
  coelhos: {
    handle: "@coelhosdamontanha",
    subtitulo: "Raças e filhotes disponíveis.",
    url: "https://instagram.com/coelhosdamontanha",
  },
};
